#!/bin/zsh

# Link .rcola files to true rc files
ln -s ~/.rcola/zshrc ~/.zshrc
ln -s ~/.rcola/vimrc ~/.vimrc

# Tell git that local rc file changes can be ignored
git -C ~/.rcola update-index --assume-unchanged local/*

# Make vim directories
mkdir -p ~/.vim/autoload
mkdir -p ~/.vim/bundle
mkdir -p ~/.vim/colors
mkdir -p ~/.vim/undo
mkdir -p ~/.vim/swap

if [[ ! -e ~/.vim/ftplugin ]] ; then
  ln -s ~/.rcola/vim/ftplugin ~/.vim/ftplugin
else
  echo ~/.vim/ftplugin already exists, not symlinking
fi

# Install vim pathogen
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

# Install vim pathogen modules
cd ~/.vim/bundle
git clone git://github.com/godlygeek/tabular.git
git clone git://github.com/sjrct/detectindent.git
git clone git://github.com/kien/ctrlp.vim.git
git clone git://github.com/vim-scripts/vim-stylus.git
git clone git://github.com/tpope/vim-fugitive.git
vim -u NONE -c "helptags vim-fugitive/doc" -c q

# Install moonshine colorscheme
curl -LSso ~/.vim/colors/moonshine.vim https://raw.githubusercontent.com/KKPMW/moonshine-vim/master/colors/moonshine.vim

# Generic git config stuff
#   Credits:
#     lg1, lg2 - Slipp D. Thompson (stackoverflow)
#     ll - durdn
git config --global push.default current
git config --global alias.lg1 "log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all"
git config --global alias.lg2 "log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold cyan)%aD%C(reset) %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset)%n'' %C(white)%s%C(reset) %C(dim white)- %an%C(reset)' --all"
git config --global alias.lg '!git lg2'
git config --global alias.ll 'log --pretty=format:"%C(yellow)%h%Cred%d\\ %Creset%s%Cblue\\ [%cn]" --decorate --numstat'
git config --global alias.go checkout
git config --global alias.df 'diff --color'

