#!/bin/zsh

# Link .rccola files to true rc files
ln -s ~/.rccola/zshrc ~/.zshrc
ln -s ~/.rccola/vimrc ~/.vimrc

# Tell git that local rc file changes can be ignored
git -C ~/.rccola update-index --assume-unchanged local/*

# Make vim directories
mkdir -p ~/.vim/autoload
mkdir -p ~/.vim/bundle
mkdir -p ~/.vim/undo
mkdir -p ~/.vim/swap

ln -s ~/.rccola/vim/ftplugin ~/.vim/ftplugin

# Install vim pathogen
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

# Install vim pathogen modules
cd ~/.vim/bundle
git clone git://github.com/godlygeek/tabular.git

